fix: 배포 스크립트 헬스체크 수정

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -118,18 +118,18 @@ jobs:
             
             ## 서버 헬스 체크
             TARGET_URL=localhost PORT=8080
-
+            
             for RETRY_COUNT in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
               echo "> #${RETRY_COUNT} trying..."
-              RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" $TARGET_URL:$PORT/health)
-
+              RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" $TARGET_URL:$PORT/health || true)
+            
               if [ "${RESPONSE_CODE}" -eq 200 ]; then
                 echo "> New WAS successfully running"
                 exit 0
-              elif [ ${RETRY_COUNT} -eq 10 ]; then
-                echo "> Health check failed."
-                exit 1
               fi
               sleep 10
             done
             
+            echo "> Health check failed."
+            exit 1
+                        
